version: '2'
services:
  backend:
    build: backend/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/slm
    ports:
      - "8000:8000"
    expose:
      - "8000"
  frontend:
    build: frontend/
    command: npm run start
    volumes:
      - ./frontend:/slm
      - /slm/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - backend
